---
  - name: Populate /etc/environment
    lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}"
      line: '{{ item.key }}="{{ item.value}}"'
    with_items: ["{{ os_environment }}", "{{ os_environment_secrets }}"]
    become: yes