---
  - name: Install the package "mongodb"
    apt:
      name: mongodb
    become: yes  

#TO-DO: Check unrestricted db access  
  - name: Allow all access to tcp port 80
    ufw:
      rule: allow
      port: "{{ mongo.port }}"
    become: yes

  - name: Install the package "python3-pip"
    apt:
      name: python3-pip
    become: yes  

  - name: Install pip
    become: yes
    apt:
      name: python-pip
      state: present

  - name: Install the Python pymongo module
    become: yes
    pip: 
      name: pymongo
      executable: /usr/bin/pip3

  - name: Create a new user
    mongodb_user:
      database: "{{ mongo.database }}"
      user: "{{ mongo.username }}"
      password: "{{ mongo_secrets.user_password }}"
      state: present
      roles:
        - db: "{{ mongo.database }}"
          role: "{{ mongo.role }}"
    become: yes

