---
  - name: "Check if nodejs is already installed"
    stat:
      path: "{{ nodejs.dir }}/bin/node"
    register: nodejs_available

  - name: "Download and unarchive nodejs {{ nodejs.version }}"
    unarchive:
      src: "{{ nodejs.url }}"
      dest: "{{ nodejs.base }}"
      remote_src: yes
      owner: "{{ nodejs.owner }}"
      group: "{{ nodejs.group }}"
    become: true
    when: nodejs_available.stat.exists == false

  - name: "Create symlink to current version"
    file:
      path: "{{ nodejs.home }}"
      src: "{{ nodejs.dir }}"
      state: link
      owner: "{{ nodejs.owner }}"
      group: "{{ nodejs.group }}"
    become: true

  - name: "Create /usr/bin links"
    file:
      path: "/usr/bin/{{ item }}"
      src: "{{ nodejs.home }}/bin/{{ item }}"
      state: link
    with_items:
      - node
      - npm
    become: true